version: '3'

services:
  db:
    image: 'postgres:12.0'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  website:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/myapp'
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=''
      - DB_HOST=db
  webpacker:
    build: .
    env_file:
      - '.env'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/myapp
    ports:
      - '3035:3035'
